services:
    ldapproxy:
        networks:
            uninuvola:
                ipv4_address: ${LDAPPROXY_IP}
        container_name: ldapproxy
        image: harbor1.fisgeo.unipg.it/uninuvola/ldapproxy:latest
        command: /ldapproxy -d -config /data/config.yaml
        env_file: ../.env
        volumes:
            - ./:/data/
networks:
  uninuvola:
    external: true
